# Generated by Django 3.2.4 on 2021-07-13 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Edemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_choice', models.CharField(choices=[('one', 'one'), ('two', 'two')], default=1, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=100)),
                ('pro_price', models.BigIntegerField()),
                ('pro_offer_price', models.BigIntegerField(default=0)),
                ('pro_fake_price', models.BigIntegerField(blank=True, null=True)),
                ('pro_image', models.FileField(blank=True, upload_to='')),
                ('pro_description', models.TextField(blank=True, null=True)),
                ('pro_star', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True)),
                ('pro_availability', models.BooleanField(default=True)),
                ('pro_cat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.category')),
                ('pro_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.color')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_list_status', models.BooleanField(default=False)),
                ('wish_list_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
                ('wish_list_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='pro_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.size'),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_quantity', models.IntegerField(default=1)),
                ('cart_status', models.BooleanField(default=False)),
                ('cart_price', models.IntegerField(blank=True, null=True)),
                ('cart_date', models.DateTimeField(auto_now_add=True)),
                ('cart_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
                ('cart_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
