# Generated by Django 3.2.4 on 2021-07-13 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.color'),
        ),
    ]
