# Generated by Django 3.2.4 on 2021-07-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='post_image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='postimage',
            name='post_image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.ImageField(height_field='post_image_height', upload_to='images/', width_field='post_image_width'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_image',
            field=models.ImageField(blank=True, height_field='image_height', upload_to='images/', width_field='image_width'),
        ),
    ]
