# Generated by Django 3.2.4 on 2021-07-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20210730_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post_image_height',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='post_image_width',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
