# Generated by Django 3.2.4 on 2021-07-19 17:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_product_pro_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_star',
            field=multiselectfield.db.fields.MultiSelectField(max_length=3, null=True),
        ),
    ]
