# Generated by Django 3.2.4 on 2021-07-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_product_pro_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_star',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
    ]
