# Generated by Django 3.2.4 on 2021-07-20 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_product_pro_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Size', models.CharField(choices=[('XXL', 'XXL'), ('XL', 'XL'), ('L', 'L')], default=('L', 'L'), max_length=50)),
                ('size_key', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
