# Generated by Django 3.2.4 on 2021-07-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pro_size',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
