# Generated by Django 3.2.4 on 2021-07-20 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_auto_20210720_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Color', models.CharField(choices=[('red', 'red'), ('black', 'black'), ('gray', 'gray'), ('yellow', 'yellow')], default=('gray', 'gray'), max_length=50)),
                ('color_key', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
