# Generated by Django 3.2.4 on 2021-07-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pro_color',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
