# Generated by Django 3.2.4 on 2021-07-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_auto_20210720_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
