# Generated by Django 3.2.4 on 2021-07-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_cart_cart_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
