# Generated by Django 3.2.4 on 2021-07-24 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_product', models.CharField(max_length=20, null=True)),
                ('ord_size', models.CharField(max_length=20)),
                ('ord_color', models.CharField(max_length=20)),
                ('ord_quantity', models.CharField(max_length=20)),
                ('ord_date', models.DateTimeField(auto_now_add=True)),
                ('ord_pro_price', models.IntegerField(blank=True, null=True)),
                ('ord_status', models.BooleanField(default=False)),
                ('ord_payment_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=40, null=True)),
                ('ammount', models.CharField(max_length=40)),
                ('payment_id', models.CharField(max_length=100)),
                ('paid', models.BooleanField(default=False)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
