# Generated by Django 3.2.4 on 2021-07-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_history',
            name='ord_pro_price',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
