# Generated by Django 3.2.4 on 2021-07-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_order_history_ord_pro_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_history',
            name='ord_pro_price',
        ),
    ]
