# Generated by Django 3.2.4 on 2021-07-24 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Order', '0003_remove_order_history_ord_pro_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_history',
            name='history_user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_user_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
