# Generated by Django 3.2.4 on 2021-08-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_checkout_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='order_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='order_comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order_history',
            name='ord_product',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
