# Generated by Django 3.2.4 on 2021-07-28 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_order_history_history_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_history',
            name='order_checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='History_Checkout', to='Order.checkout'),
        ),
    ]
